#
# This file is part of LCCS-WS.
# Copyright (C) 2022 INPE.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.
#

kind: pipeline
name: lccs-ws

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: python:3.7
  commands:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -e .[tests,docs]
  - lccs-db db init
  - lccs-db db create-namespaces
  - lccs-db db create-extension-hstore
  - lccs-db alembic upgrade
  - lccs-db db load-scripts
  - ./run-tests.sh
  environment:
    SQLALCHEMY_DATABASE_URI: postgresql://postgres:mysecretpassword@pg_database:5432/bdc_db

- name: coverage
  image: plugins/codecov
  settings:
    files:
    - coverage.xml
    - .coverage
    token:
      from_secret: codecov_token
  when:
    event:
    - push

- name: discord-notify
  image: brazildatacube/bdc-drone-discord
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status:
    - failure
    - success

- name: docker-registry
  image: plugins/docker
  settings:
    auto_tag: true
    custom_dns: 150.163.2.4
    password:
      from_secret: registry_pass
    registry: registry.dpi.inpe.br
    repo: registry.dpi.inpe.br/${DRONE_REPO}
    username:
      from_secret: registry_user

services:
- name: pg_database
  image: postgis/postgis:13-3.1
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: postgres

