#
# This file is part of Land Cover Classification System Web Service.
# Copyright (C) 2020-2021 INPE.
#
# Land Cover Classification System Web Service is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

kind: pipeline
name: lccs-ws

steps:
- name: build
  image: python:3.7
  commands:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install -e .[tests,docs]
  - lccs-db db init
  - lccs-db db create-namespaces
  - lccs-db alembic upgrade
  - lccs-db db load-scripts
  - ./run-tests.sh
  environment:
    SQLALCHEMY_DATABASE_URI: postgresql://postgres:mysecretpassword@pg_database:5432/bdc_db

- name: coverage
  image: plugins/codecov
  settings:
    files:
    - coverage.xml
    - .coverage
    token:
      from_secret: codecov_token
  when:
    event:
    - push

- name: discord-notify
  image: brazildatacube/bdc-drone-discord
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status:
      - failure
      - success

- name: docker-registry
  image: plugins/docker
  network_mode: bridge
  settings:
    repo: registry.dpi.inpe.br/${DRONE_REPO}
    registry: registry.dpi.inpe.br
    username:
      from_secret: registry_user
    password:
      from_secret: registry_pass
    auto_tag: true

services:
- name: pg_database
  image: postgis/postgis:13-3.1
  environment:
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: postgres
