sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip

dist: bionic

python:
    - "3.7"

env:
  matrix:
  - BASE_URL="http://localhost:5000"

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade wheel

install:
    - pip install -e .[tests,docs]

script:
    - ./run-tests.sh

after_success:
    - coveralls