language: python

cache:
    directories:
        - $HOME/.cache/pip

branches:
    only:
        - master
        - b-0.2

dist: bionic

python:
    - "3.7"

env:
  matrix:
  - BASE_URL="http://localhost:5000"
  - SQLALCHEMY_DATABASE_URI="postgresql://postgres:postgres@127.0.0.1:5432/bdc_lccs"


before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools

install:
    - pip install -e .[tests,docs]
    - docker pull postgis/postgis:12-3.0
    - docker run --name bdc_lccs -p 127.0.0.1:5432:5432 -e POSTGRES_PASSWORD=postgres -d postgis/postgis:12-3.0
    - docker ps -a

script:
    - ./run-tests.sh

after_success:
    - docker stop bdc-pg
    - docker rm bdc-pg
    - coveralls